Импортировать NumPy под именем np:

In [21]:
import numpy as np

Напечатать версию и конфигурацию:

In [22]:
print(np.__version__)
np.show_config()

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\

Создать вектор (одномерный массив) размера 10, заполненный нулями:

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Создать вектор размера 10, заполненный единицами:

In [24]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Создать вектор размера 10, заполненный числом 2.5:

In [25]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

Как получить документацию о функции numpy.add из командной строки?

In [26]:
help(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array o

Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1:

In [27]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Создать вектор со значениями от 10 до 49:

In [28]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

Развернуть вектор (первый становится последним):

In [29]:
a = np.arange(10, 20)
np.flipud(a)

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8:

In [30]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Найти индексы ненулевых элементов в [1,2,0,0,4,0]:

In [31]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

Создать массив 3x3x3 со случайными значениями:

In [32]:
np.random.sample((3, 3, 3))

array([[[0.06866451, 0.60649009, 0.66487954],
        [0.65380369, 0.74880247, 0.59349267],
        [0.30407379, 0.76819626, 0.83812218]],

       [[0.85749802, 0.74044607, 0.75931355],
        [0.13662711, 0.88118615, 0.6308269 ],
        [0.69360141, 0.51061025, 0.46619885]],

       [[0.62360281, 0.50043327, 0.89110598],
        [0.58965201, 0.85549405, 0.2669597 ],
        [0.53535756, 0.56393401, 0.1503889 ]]])

Создать массив 10x10 со случайными значениями, найти минимум и максимум:

In [33]:
a = np.random.sample((10, 10))
print(a)
print(a.min())
print(a.max())

[[0.85395999 0.42903241 0.33886845 0.5717211  0.67746815 0.00827776
  0.56850361 0.11099849 0.67720636 0.10528923]
 [0.753844   0.43926137 0.56443005 0.469626   0.33628861 0.53387517
  0.92661542 0.04765662 0.54228996 0.05900093]
 [0.60557149 0.17281942 0.53550375 0.1079083  0.26395473 0.35465572
  0.93870124 0.31579284 0.2680988  0.1346078 ]
 [0.38814265 0.00388519 0.15405469 0.75683071 0.65281782 0.20096733
  0.05504464 0.90811042 0.98781449 0.54520404]
 [0.35763602 0.44066439 0.20347984 0.56572448 0.8954211  0.62935131
  0.33326352 0.09798233 0.50473917 0.44669302]
 [0.44308287 0.69606467 0.46468018 0.77079888 0.56333439 0.73018692
  0.64391859 0.84706292 0.48709946 0.08899242]
 [0.87397519 0.72725321 0.86399188 0.7608879  0.46793818 0.37670464
  0.43097185 0.55047019 0.25957399 0.33351401]
 [0.70166963 0.55026345 0.69822609 0.76510852 0.39896749 0.97252518
  0.41034271 0.92711168 0.66347851 0.91892977]
 [0.49995108 0.01298233 0.48005791 0.80149465 0.37290697 0.20919611
  0.70330015

Создать случайный вектор размера 30 и найти среднее значение всех элементов:

In [34]:
a = np.random.sample(30)
print(a)
np.average(a)

[0.45736227 0.5382112  0.66268551 0.67886168 0.45157238 0.10305564
 0.33858862 0.77535878 0.51515389 0.9992013  0.19939029 0.36654002
 0.26700045 0.63470296 0.6068337  0.69722465 0.22931924 0.91820363
 0.79397614 0.32533791 0.75650345 0.36407749 0.53917538 0.19341197
 0.68473006 0.96965937 0.65861648 0.30923018 0.52883554 0.64851463]


0.5403778267520583

Создать матрицу с 0 внутри, и 1 на границах:

In [35]:
a = np.ones((10, 10))
a[1:-1,1:-1] = np.zeros((8, 8))
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Выяснить результат следующих выражений:
1) 0 * np.nan
2) np.nan == np.nan
3) np.inf > np.nan
4) np.nan - np.nan

In [36]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)

nan
False
False
nan


Создать 5x5 матрицу с 1,2,3,4 под диагональю:

In [41]:
print(np.diag(np.arange(1,5), k = -1))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


Создать 8x8 матрицу и заполнить её в шахматном порядке:

In [42]:
a = np.zeros((8,8))
for i in range(8):
    for j in range(8):
        if((i + j) % 2 == 0):
            a[i, j] = 1
print(a)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [43]:
print(np.unravel_index(100, (6, 7, 8)))

(1, 5, 4)


Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile:

In [44]:
a = np.array(([1, 0], [0, 1]))
print(np.tile(a, [4, 4]))

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
