---
                                            Московский Авиационный Институт  
                                      (Национальный Исследовательский Университет)  
        
                
                
    Кафедра 806 «Вычислительная математика и программирование»  
    Институт: «Информационные технологии и прикладная математика»  
    Дисциплина: «Разработка ПО для высокопроизводительных систем»        
                


                                            -------------------------------
                                            Лабораторная работа по NumPy №2  
                                            -------------------------------    
                                            
                                            
                                            
                                                                                Группа: М8О-103М-20  
                                                                                Студент: Ларин Антон Владимирович  
                                                                                Преподаватель: Поповкин Александр Викторович  
                                                                                
                                                                                
                                                                                
                                                     Москва, 2020  
                                                         
---

Импорт необходимых библиотек и установка настроек вывода данных:

In [2]:
import numpy as np
import sys
import scipy.spatial
np.set_printoptions(linewidth=200, precision=3)

Перемножить матрицы 5x3 и 3x2:

In [192]:
a = np.array(([1,2,3],[1,2,3],[1,2,3],[1,2,3],[1,2,3]))
b = np.array(([1,2],[1,2],[1,2]))
print(a.dot(b))

[[ 6 12]
 [ 6 12]
 [ 6 12]
 [ 6 12]
 [ 6 12]]


Дан массив, поменять знак у элементов, значения которых между 3 и 8:

In [193]:
a = np.arange(10)
print(a)
a[(3 < a) & (a < 8)] *= -1
print(a)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3 -4 -5 -6 -7  8  9]


Создать 5x5 матрицу со значениями в строках от 0 до 4:

In [194]:
a = np.zeros((5,5)) + np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


Есть генератор, сделать с его помощью массив:

In [195]:
def gen(n):
    for x in range(n):
        yield x
        
a = np.fromiter(gen(10),dtype=int)
print(a)

[0 1 2 3 4 5 6 7 8 9]


Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое:

In [196]:
a = np.linspace(0,1,12)[1:-1]
print(a)

[0.091 0.182 0.273 0.364 0.455 0.545 0.636 0.727 0.818 0.909]


Отсортировать вектор:

In [197]:
a = np.random.sample(10)
print(a)
a.sort()
print(a)

[0.722 0.267 0.794 0.936 0.042 0.867 0.333 0.765 0.085 0.723]
[0.042 0.085 0.267 0.333 0.722 0.723 0.765 0.794 0.867 0.936]


Проверить, одинаковы ли 2 numpy массива:

In [198]:
a = np.array([1,2,3])
b = np.array([1,2,3])
c = np.array([-1,-2,-3])
print(np.allclose(a,b))
print(np.allclose(a,c))

True
False


Сделать массив неизменяемым:

In [199]:
a = np.ones(5)
a.flags.writeable = False
a[0] = 0

ValueError: assignment destination is read-only

Дан массив 10x2 (точки в декартовой системе координат), преобразовать в полярную:

In [200]:
a = np.ones((10,2))
print(a)
x, y = a[:,0], a[:,1]
r = np.hypot(x, y)
t = np.arctan2(y, x)
print(r)
print(t)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[1.414 1.414 1.414 1.414 1.414 1.414 1.414 1.414 1.414 1.414]
[0.785 0.785 0.785 0.785 0.785 0.785 0.785 0.785 0.785 0.785]


Заменить максимальный элемент на ноль:

In [201]:
a = np.random.sample(5)
print(a)
a[a.argmax()] = 0
print(a)

[0.75  0.031 0.438 0.558 0.726]
[0.    0.031 0.438 0.558 0.726]


Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]:

In [202]:
n = 8
a = np.zeros((n, n), [('x', float), ('y', float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0, 1, n),
                             np.linspace(0, 1, n))
print(a)

[[(0.   , 0.   ) (0.143, 0.   ) (0.286, 0.   ) (0.429, 0.   ) (0.571, 0.   ) (0.714, 0.   ) (0.857, 0.   ) (1.   , 0.   )]
 [(0.   , 0.143) (0.143, 0.143) (0.286, 0.143) (0.429, 0.143) (0.571, 0.143) (0.714, 0.143) (0.857, 0.143) (1.   , 0.143)]
 [(0.   , 0.286) (0.143, 0.286) (0.286, 0.286) (0.429, 0.286) (0.571, 0.286) (0.714, 0.286) (0.857, 0.286) (1.   , 0.286)]
 [(0.   , 0.429) (0.143, 0.429) (0.286, 0.429) (0.429, 0.429) (0.571, 0.429) (0.714, 0.429) (0.857, 0.429) (1.   , 0.429)]
 [(0.   , 0.571) (0.143, 0.571) (0.286, 0.571) (0.429, 0.571) (0.571, 0.571) (0.714, 0.571) (0.857, 0.571) (1.   , 0.571)]
 [(0.   , 0.714) (0.143, 0.714) (0.286, 0.714) (0.429, 0.714) (0.571, 0.714) (0.714, 0.714) (0.857, 0.714) (1.   , 0.714)]
 [(0.   , 0.857) (0.143, 0.857) (0.286, 0.857) (0.429, 0.857) (0.571, 0.857) (0.714, 0.857) (0.857, 0.857) (1.   , 0.857)]
 [(0.   , 1.   ) (0.143, 1.   ) (0.286, 1.   ) (0.429, 1.   ) (0.571, 1.   ) (0.714, 1.   ) (0.857, 1.   ) (1.   , 1.   )]]


Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj)):

In [203]:
x = np.arange(8)
y = x + 10
c = 1 / np.subtract.outer(x, y)
print(c)

[[-0.1   -0.091 -0.083 -0.077 -0.071 -0.067 -0.062 -0.059]
 [-0.111 -0.1   -0.091 -0.083 -0.077 -0.071 -0.067 -0.062]
 [-0.125 -0.111 -0.1   -0.091 -0.083 -0.077 -0.071 -0.067]
 [-0.143 -0.125 -0.111 -0.1   -0.091 -0.083 -0.077 -0.071]
 [-0.167 -0.143 -0.125 -0.111 -0.1   -0.091 -0.083 -0.077]
 [-0.2   -0.167 -0.143 -0.125 -0.111 -0.1   -0.091 -0.083]
 [-0.25  -0.2   -0.167 -0.143 -0.125 -0.111 -0.1   -0.091]
 [-0.333 -0.25  -0.2   -0.167 -0.143 -0.125 -0.111 -0.1  ]]


Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy:

In [204]:
for dtype in [np.int8, np.int32, np.int64]:
    print(dtype, np.iinfo(dtype).min, np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(dtype, np.finfo(dtype).min, np.finfo(dtype).max)

<class 'numpy.int8'> -128 127
<class 'numpy.int32'> -2147483648 2147483647
<class 'numpy.int64'> -9223372036854775808 9223372036854775807
<class 'numpy.float32'> -3.4028235e+38 3.4028235e+38
<class 'numpy.float64'> -1.7976931348623157e+308 1.7976931348623157e+308


Напечатать все значения в массиве:

In [209]:
a = np.ones((20,20))
np.set_printoptions(threshold=sys.maxsize)
print(a)
np.set_printoptions(threshold=100)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.

Найти ближайшее к заданному значению число в заданном массиве:

In [210]:
a = np.arange(10)
value = np.random.uniform(0,10)
print(value)
closest = abs(a-value).argmin()
print(a[closest])

1.2295410872554269
1


Создать структурированный массив, представляющий координату (x,y) и цвет (r,g,b):

In [211]:
a = np.zeros(5, [('position', [('x', float), ('y', float)]), 
                 ('color', [('r', int), ('g', int), ('b', int)])])
print(a)

[((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0))]


Дан массив (100,2) координат, найти расстояние от каждой точки до каждой:

In [212]:
dots = np.random.random((100, 2))
print(dots)
d = scipy.spatial.distance.cdist(dots, dots)
print(d)

[[0.033 0.751]
 [0.628 0.909]
 [0.574 0.246]
 ...
 [0.34  0.21 ]
 [0.223 0.278]
 [0.365 0.422]]
[[0.    0.616 0.74  ... 0.622 0.51  0.468]
 [0.616 0.    0.665 ... 0.757 0.75  0.554]
 [0.74  0.665 0.    ... 0.237 0.352 0.273]
 ...
 [0.622 0.757 0.237 ... 0.    0.135 0.213]
 [0.51  0.75  0.352 ... 0.135 0.    0.202]
 [0.468 0.554 0.273 ... 0.213 0.202 0.   ]]


Преобразовать массив из float в int:

In [213]:
a = np.arange(10, dtype=np.float32)
print(a)
a = a.astype(np.int32)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


Дан файл:
1,2,3,4,5
6,,,7,8
,,9,10,11
Как прочитать его?

In [214]:
print(np.genfromtxt("lab2data.txt", delimiter=","))

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


Каков эквивалент функции enumerate для numpy массивов?

In [215]:
a = np.arange(4).reshape(2, 2)
for index, value in np.ndenumerate(a):
    print(index, value)
print()
for index in np.ndindex(a.shape):
    print(index, a[index])

(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3

(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3


Сформировать 2D массив с распределением Гаусса:

In [216]:
a = np.random.normal(1, 0.1, (5, 5))
print(a)

[[0.967 0.845 0.955 1.065 1.067]
 [1.097 1.086 0.938 1.09  0.913]
 [0.937 0.963 1.136 1.068 1.03 ]
 [0.906 0.924 1.165 1.068 1.062]
 [0.931 0.77  1.085 1.031 1.065]]


Случайно расположить p элементов в 2D массив:

In [224]:
p = 5
a = np.zeros((p,p))
np.put(a, np.random.choice(range(p * p), p, replace=False), 1)
print(a)

[[0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]]


Отнять среднее из каждой строки в матрице:

In [225]:
a = np.random.rand(3, 3)
print(a)
print(a.mean(axis = 1))
a = a - a.mean()
print(a)

[[0.485 0.532 0.952]
 [0.66  0.557 0.59 ]
 [0.599 0.547 0.566]]
[0.656 0.602 0.571]
[[-0.125 -0.078  0.343]
 [ 0.05  -0.053 -0.02 ]
 [-0.01  -0.063 -0.044]]


Отсортировать матрицу по n-ому столбцу:

In [3]:
a = np.random.rand(5,5)
n = 2
print(a)
print(a[a[:,n].argsort()])
print(a[[0,2,1]])

[[0.142 0.705 0.054 0.415 0.419]
 [0.34  0.815 0.889 0.151 0.874]
 [0.013 0.886 0.798 0.768 0.315]
 [0.749 0.238 0.637 0.699 0.707]
 [0.581 0.078 0.24  0.887 0.676]]
[[0.142 0.705 0.054 0.415 0.419]
 [0.581 0.078 0.24  0.887 0.676]
 [0.749 0.238 0.637 0.699 0.707]
 [0.013 0.886 0.798 0.768 0.315]
 [0.34  0.815 0.889 0.151 0.874]]
[[0.142 0.705 0.054 0.415 0.419]
 [0.013 0.886 0.798 0.768 0.315]
 [0.34  0.815 0.889 0.151 0.874]]


Определить, есть ли в 2D массиве нулевые столбцы:

In [227]:
a = np.random.randint(0, 2, (3, 10))
print(a)
print((~a.any(axis = 0)))
print((~a.any(axis = 0)).any())

[[0 0 0 1 0 1 0 1 0 0]
 [0 1 0 1 0 0 1 0 1 1]
 [1 1 0 0 1 0 1 0 0 1]]
[False False  True False False False False False False False]
True


Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами):

In [228]:
a = np.ones(10)
print(a)
index = np.random.randint(0, len(a), 10)
print(index)
for i in range(len(a)):
    if i in index:
        a[i] += 1
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0 8 0 4 5 9 0 6 4 2]
[2. 1. 2. 1. 2. 2. 2. 1. 2. 2.]


Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов:

In [229]:
w, h = 128, 128
I = np.random.randint(0,2,(w,h,3)).astype(np.ubyte)
F = I[...,0]*4 + I[...,1]*2 + I[...,2]
print(len(np.unique(F)))

8


Дан четырехмерный массив, посчитать сумму по последним двум осям:

In [230]:
a = np.random.randint(0, 10, (2,2,3,3))
print(a)
sum = a.sum(axis=(-2,-1))
print(sum)

[[[[7 5 5]
   [1 9 1]
   [1 7 2]]

  [[7 8 2]
   [3 7 4]
   [9 5 2]]]


 [[[9 7 6]
   [6 6 0]
   [2 8 8]]

  [[4 0 4]
   [5 1 5]
   [7 7 2]]]]
[[38 47]
 [52 35]]


Найти диагональные элементы произведения матриц:

In [231]:
a = np.random.randint(0, 5, (3, 3))
print(a)
b = np.random.randint(0, 5, (3, 3))
print(b)
print(np.diag(a.dot(b)))

[[3 4 4]
 [4 1 4]
 [4 0 4]]
[[1 3 3]
 [3 2 0]
 [4 3 1]]
[31 26 16]
